pipeline {
    agent any

    stages {
        stage('Installation') {
            steps {
                script {
                    // Install dependencies
                    sh "python3 -m pip install coverage"
                    sh "coverage --version"
                }
            }
        }

        stage('Run Test') {
            environment {
                PYTHON_FILE = 'path/to/test.py'
            }
            steps {
                script {
                    // Run tests and Generate reports
                    sh "pip install -r requirements.txt"
                    sh "coverage run ${PYTHON_FILE}"
                    sh "coverage report"
                    sh "coverage xml -o coverage.xml"
                }
            }
        }

        stage('Code Analysis') {
            environment {
                SCANNER_HOME  = tool 'sonar_scanner_name'
                PROJECT_KEY   = ''
                PROJECT_NAME  = ''
            }
            steps {
                script {
                    withSonarQubeEnv('sonarcloud_server') {
                        sh """${SCANNER_HOME}/bin/sonar-scanner \
                        -Dsonar.projectKey=${PROJECT_KEY} \
                        -Dsonar.projectName=${PROJECT_NAME} \
                        -Dsonar.python.coverage.reportPaths=coverage.xml"""
                    }
                }
            }
        }
    }
}