pipeline {
    agent any

    tools {
        maven 'Maven_Installation_Name'
    }

    stages {
        stage('Test') {
            steps {
                script {
                    sh "mvn clean test"
                }
            }
        }

        stage('Code Analysis') {
            environment {
                PROJECT_KEY   = ''
                PROJECT_NAME  = ''
                SONAR_TOKEN   = ''
            }
            steps {
                script {
                    sh """mvn clean verify \
                    -Dsonar.projectKey=${PROJECT_KEY} \
                    -Dsonar.projectName=${PROJECT_NAME} \ 
                    -Dsonar.token=${SONAR_TOKEN} """
                }
            }
        }
    }
}